### ISSUE TITLE
Disconnected issue

### ISSUE THREAD

**Issue by pooo900** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#37]
When I join it keeps saying socket timed out and when I disable the hack its normal

**Comment by DwayneTheRock** [comment]
The game updated, so you'll have to wait for a new version of the hack to be released.

**Comment by RayanAlami** [comment]
I am sorry guys, but lately, krunker has been really hard to hack and I am soon going to partner up with some people to help me hack the game. Please wait a few days and that's when the hack will be fixed. I am very sorry but don't worry, press 'watch' on top next to 'star' to get notified of the latest update, if the problem was fixed, or what new features there are is this amazing hack!!!
